// src/integrations/supabase/client.ts
// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izeheflwfguwinizihmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6ZWhlZmx3Zmd1d2luaXppaG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDAyNzEsImV4cCI6MjA3MjUxNjI3MX0.s243LZphO7lOUqqsYQrBjZg62WjenonPZrgrzjzqjVM";

// Create ONE client instance and cache it on globalThis to avoid duplicates (HMR/code-splitting)
function makeClient(): SupabaseClient<Database> {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      headers: { 'x-client-info': 'splikz-web' },
    },
  });
}

const g = globalThis as unknown as { __sb?: SupabaseClient<Database> };
export const supabase: SupabaseClient<Database> = g.__sb ?? (g.__sb = makeClient());
